server:
  port: 80
  servlet:
    context-path: /
  #链接建立超时时间ms
  connection-timeout: 12000
  tomcat:
    uri-encoding: UTF-8
    #最小线程数
    min-spare-threads: 100
    #最大线程数 CUP核心数的200~250倍之间
    max-threads: 230
    #最大等待队列长度
    accept-count: 70
    #最大链接数
    max-connections: 300
    #请求头最大长度kb
    max-http-header-size: 1048576
    #请请求体最大长度kb
    #max-http-post-size: 2097152

wx:
  appid: wxd8e954dce20c1a51
  secret: fba8753b463ff4f1046ef3bc55150404

logging:
  config: classpath:logback-spring.xml
  level:
    org: info
    com: info

aysnc:
  task:
    cron: 0/5 * * * * ?

file:
  path:
    upload: E:/tmp

spring:
  application:
    name: wwzq-backend
  datasource:
    username: root
    password: Zyli*M1fX%09q
    url: jdbc:mysql://192.168.1.47:3417/olmn?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
#    redis:
#      database: 1
#      # Redis服务器地址
#      host: 47.107.56.61
#      # Redis服务器连接端口
#      port: 6379
#      # Redis服务器连接密码（默认为空）
#      password:
#      # 连接超时时间（毫秒）
#      timeout: 1000
#      # 连接池最大连接数（使用负值表示没有限制）
#      pool:
#        max-active: 200
#        # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: -1
#        # 连接池中的最大空闲连接
#        max-idle: 10
#        # 连接池中的最小空闲连接
#        min-idle: 0


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ren.wwzq.dao
  mapper: com.karle.tk.TkMapper
  identity: MYSQL
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql
pageSize: 10





